# Generated by Django 5.0.3 on 2024-04-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='destination_preview',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Detailed_desc',
        ),
        migrations.DeleteModel(
            name='NetBanking',
        ),
        migrations.DeleteModel(
            name='pessanger_detail',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
