# Generated by Django 5.0.3 on 2024-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0007_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'In Review'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (3, '★★★☆☆'), (5, '★★★★★'), (2, '★★☆☆☆'), (4, '★★★★☆')], default=None),
        ),
    ]
