# Generated by Django 5.0.3 on 2024-05-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0008_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (4, '★★★★☆'), (5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
