# Generated by Django 5.0.3 on 2024-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0009_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='5.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'In Review'), ('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (5, '★★★★★')], default=None),
        ),
    ]
