# Generated by Django 5.0.3 on 2024-04-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0010_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('in_review', 'In Review'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (2, '★★☆☆☆'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
