# Generated by Django 5.0.3 on 2024-05-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0012_alter_product_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆')], default=None),
        ),
    ]
