# Generated by Django 5.0.3 on 2024-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0015_alter_product_image_alter_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (2, '★★☆☆☆'), (5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
