# Generated by Django 5.0.3 on 2024-04-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0017_alter_product_image_alter_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product_thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (3, '★★★☆☆'), (4, '★★★★☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='vendor_pp'),
        ),
    ]
