# Generated by Django 5.0.3 on 2024-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0018_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='otp_code',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (3, '★★★☆☆'), (2, '★★☆☆☆'), (5, '★★★★★'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
