# Generated by Django 5.0.3 on 2024-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0020_rename_date_product_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (1, '★☆☆☆☆'), (5, '★★★★★'), (3, '★★★☆☆'), (4, '★★★★☆')], default=None),
        ),
    ]
