# Generated by Django 5.0.3 on 2024-04-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0023_alter_product_product_status_alter_product_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'In Review'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (5, '★★★★★')], default=None),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
